
import type { Metadata } from "next";
import PageUpButton from "./components/PageUpButton";
import Providers from "./Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "GoPet",
  description: "Generated by Stella An",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundImage: "url('/images/gopet2_back.png')", backgroundSize: '70%',
      backgroundPosition: 'center', backgroundRepeat: 'repeat',}}>
        <Providers>
          {children}
        </Providers>
        <PageUpButton />
      </body>
    </html>
  );
}
